#!/usr/bin/env python3
# @dependency-start
# contract tool
# responsibility Dispatches generated runtime Skill readback to catalog schema and materializer owners.
# upstream implementation ../../../../tools/agent/skills/skill_route_catalog.py owns native catalog schema admission
# upstream implementation ../../../../tools/agent/skills/skill_shim_materializer.py owns generated projection fixed point
# downstream implementation ../../../../.github/workflows/agent-canon-static-gates.yml runs this compatibility command
# downstream implementation ../../../../tests/agent_tools/test_check_skill_frontmatter.py verifies projection readback
# @dependency-end
"""Compatibility entrypoint for generated runtime Skill projection readback.

Runtime ``SKILL.md`` files are generated projections, not a second canonical
frontmatter source. Structural catalog admission is delegated to the local
YAML/JSON Schema tools; generated bytes are checked by the materializer's
fixed-point owner.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import cast

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from tools.agent.skills.skill_route_catalog import (
    CapabilityRootError,
    validate_catalog_schemas,
)
from tools.agent.skills.skill_shim_materializer import (
    MaterializerError,
    check as check_materialization,
)

SKILL_GLOB = ".codex/personal/skills/*/SKILL.md"


@dataclass(frozen=True)
class Finding:
    """One generated-projection readback finding."""

    check: str
    path: str
    detail: str

    def render(self) -> str:
        """Render one stable machine-readable finding."""
        return f"SKILL_FRONTMATTER_FINDING={self.check}:{self.path}:{self.detail}"


def build_parser() -> argparse.ArgumentParser:
    """Create the compatibility command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root. Defaults to cwd.")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    return parser


def skill_paths(root: Path) -> list[Path]:
    """Return generated runtime Skill projection paths in stable order."""
    return sorted(path for path in root.glob(SKILL_GLOB) if path.is_file())


def validate_root(root: Path) -> tuple[list[Finding], int]:
    """Delegate catalog admission and generated projection readback."""
    paths = skill_paths(root)
    catalog = root / "agents/skills/catalog.yaml"
    dependencies = root / "agents/skills/skill-dependencies.yaml"
    if not catalog.is_file() or not dependencies.is_file():
        return [], len(paths)
    findings: list[Finding] = []
    try:
        validate_catalog_schemas(root)
        payload = check_materialization(root, all_skills=True)
    except (CapabilityRootError, MaterializerError, OSError, ValueError) as exc:
        # Compatibility CLI keeps one fail-closed envelope.
        findings.append(Finding("projection", ".codex/personal/skills", str(exc)))
    else:
        content_delta_paths = cast(Sequence[object], payload["content_delta_paths"])
        findings.extend(
            Finding("projection", str(path), "fixed-point-drift")
            for path in content_delta_paths
        )
    return findings, len(paths)


def render_json(findings: Sequence[Finding], checked: int) -> str:
    """Render generated-projection readback output."""
    payload: Mapping[str, object] = {
        "status": "pass" if not findings else "fail",
        "checked": checked,
        "findings": [asdict(finding) for finding in findings],
    }
    return json.dumps(payload, indent=2, sort_keys=True)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the compatibility readback command."""
    args = build_parser().parse_args(argv)
    findings, checked = validate_root(Path(args.root).resolve())
    if args.format == "json":
        print(render_json(findings, checked))
    else:
        for finding in findings:
            print(finding.render())
        print(f"SKILL_FRONTMATTER_CHECKED={checked}")
        print(f"SKILL_FRONTMATTER={'pass' if not findings else 'fail'}")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
