"""Focused tests for the canonical skill runtime shim materializer."""

# @dependency-start
# contract test
# responsibility Verifies catalog-derived materializer fixed-point and readback evidence.
# upstream design ../../documents/design/skill-runtime-shim-materialization.md approved materializer contract
# upstream implementation ../../tools/agent_tools/skill_shim_materializer.py single shim writer
# downstream implementation ../../tests/fixtures/skill-runtime-shim/fixed-point/expected.json fixed-point oracle
# @dependency-end

from __future__ import annotations

import json
import os
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

PROJECT_ROOT = Path(__file__).resolve().parents[2]
TOOLS_ROOT = PROJECT_ROOT / "tools" / "agent_tools"
sys.path.insert(0, str(TOOLS_ROOT))

from skill_shim_materializer import (  # noqa: E402
    build_context,
    build_record,
    check,
    classify_legacy,
    fixed_point_acceptance,
    render_shim,
)


class SkillShimMaterializerTest(unittest.TestCase):
    """Verify materialization converges without a second writer."""

    def setUp(self) -> None:
        """Scope source-root authority to this materializer test instance."""
        parent_environment = patch.dict(
            os.environ,
            {"AGENT_CANON_PARENT_ROOT": str(PROJECT_ROOT)},
        )
        parent_environment.start()
        self.addCleanup(parent_environment.stop)

    def test_materialize_fixed_point(self) -> None:
        """Two runs preserve all records/projections and the second run is empty."""
        actual = fixed_point_acceptance(PROJECT_ROOT)
        expected = json.loads(
            (
                PROJECT_ROOT
                / "tests/fixtures/skill-runtime-shim/fixed-point/expected.json"
            ).read_text(encoding="utf-8")
        )
        self.assertEqual(actual, expected)
        self.assertEqual(actual["first_run"]["content_delta_count"], 0)
        self.assertEqual(actual["second_run"]["content_delta_count"], 0)
        self.assertTrue(actual["equal_record_digests"])
        self.assertTrue(actual["equal_projection_digests"])
        self.assertTrue(actual["equal_readback_digest"])
        self.assertEqual(
            len(actual["first_run"]["record_digests"]),
            len(actual["first_run"]["projection_digests"]),
        )
        self.assertEqual(actual["status"], "pass")

    def test_materialization_record_digest_is_read_back_from_generated_bytes(self) -> None:
        """A changed structured record digest leaves generated bytes in drift."""
        context = build_context(PROJECT_ROOT)
        skill = "agent-orchestration"
        record = build_record(context, skill)
        provenance = record["provenance"]
        if not isinstance(provenance, dict):
            raise AssertionError("record provenance is not a mapping")
        digest = provenance["record_digest"]
        if not isinstance(digest, str):
            raise AssertionError("record digest is not a string")
        runtime_path = PROJECT_ROOT / ".agents/skills" / skill / "SKILL.md"
        original = runtime_path.read_text(encoding="utf-8")
        self.assertIn(f'"record_digest":"{digest}"', original)
        runtime_path.write_text(
            original.replace(digest, "0" * 64, 1),
            encoding="utf-8",
        )
        try:
            result = check(PROJECT_ROOT, all_skills=True)
        finally:
            runtime_path.write_text(original, encoding="utf-8")
        self.assertEqual(result["status"], "fail")
        self.assertIn(runtime_path.relative_to(PROJECT_ROOT).as_posix(), result["content_delta_paths"])

    def test_legacy_classification_blocks_tool_commands_only(self) -> None:
        """Generated section-only bodies must keep all unmatched blocks and remain blocked."""
        context = build_context(PROJECT_ROOT)
        skill = "agent-orchestration"
        runtime_path = PROJECT_ROOT / ".agents/skills" / skill / "SKILL.md"
        expected = render_shim(build_record(context, skill))
        original = runtime_path.read_text(encoding="utf-8")
        runtime_path.write_text(
            "<!-- generated: agent_canon.skill_runtime_shim.v1 -->\n"
            "## Tool Commands\n"
            "python3 tools/agent_tools/skill_tool_commands.py show --skill agent-orchestration --format text\n",
            encoding="utf-8",
        )
        try:
            receipt = classify_legacy(context, skill, expected)
        finally:
            runtime_path.write_text(original, encoding="utf-8")
        self.assertEqual(receipt["resolution"], "blocked")
        self.assertEqual(receipt["classification"], "legacy_schema_mismatch")
        self.assertEqual(len(receipt["unmatched_blocks"]), 2)
        locators = [entry["locator"] for entry in receipt["unmatched_blocks"]]
        self.assertIn(
            f"{runtime_path.relative_to(PROJECT_ROOT).as_posix()}#preamble",
            locators,
        )
        self.assertIn(
            f"{runtime_path.relative_to(PROJECT_ROOT).as_posix()}#L2-L3",
            locators,
        )

    def test_legacy_receipt_lists_every_unmatched_block(self) -> None:
        """Legacy prose is rejected without a canonical-heading fallback."""
        context = build_context(PROJECT_ROOT)
        skill = "agent-orchestration"
        expected = render_shim(build_record(context, skill))
        runtime_path = PROJECT_ROOT / ".agents/skills" / skill / "SKILL.md"
        original = runtime_path.read_text(encoding="utf-8")
        runtime_path.write_text(
            "---\nname: agent-orchestration\ndescription: "
            '"Mandatory routing skill for repository tasks. Use before selecting workflow family, skills, review roles, subagents, model/team policy, runtime entrypoints, or run bundles for Codex routing."\n---\n'
            "# Legacy\n\n## Reader Map\n\nUnmatched prose.\n",
            encoding="utf-8",
        )
        try:
            receipt = classify_legacy(context, skill, expected)
        finally:
            runtime_path.write_text(original, encoding="utf-8")
        self.assertEqual(receipt["resolution"], "blocked")
        blocks = receipt["unmatched_blocks"]
        self.assertEqual(len(blocks), 2)
        self.assertTrue(all("locator" in block and "digest" in block for block in blocks))

    def test_legacy_classification_blocks_expected_section_subset(self) -> None:
        """An exact generated section subset is not a migration oracle."""
        context = build_context(PROJECT_ROOT)
        skill = "agent-orchestration"
        expected = render_shim(build_record(context, skill))
        legacy = expected
        canonical_start = legacy.index("## Canonical Skill")
        commands_start = legacy.index("## Tool Commands")
        subset = legacy[:canonical_start] + legacy[commands_start:]
        runtime_path = PROJECT_ROOT / ".agents/skills" / skill / "SKILL.md"
        original = runtime_path.read_text(encoding="utf-8")
        runtime_path.write_text(subset, encoding="utf-8")
        try:
            receipt = classify_legacy(context, skill, expected)
        finally:
            runtime_path.write_text(original, encoding="utf-8")
        self.assertEqual(receipt["classification"], "legacy_schema_mismatch")
        self.assertEqual(receipt["resolution"], "blocked")
        self.assertGreater(len(receipt["unmatched_blocks"]), 0)

    def test_legacy_classification_blocks_missing_owner_link(self) -> None:
        """A complete-looking old schema without its owner link fails closed."""
        context = build_context(PROJECT_ROOT)
        skill = "agent-orchestration"
        expected = render_shim(build_record(context, skill))
        legacy = expected
        owner_line = (
            "Canonical workflow and policy: "
            "[agent-orchestration](../../../agents/skills/agent-orchestration.md).\n"
        )
        self.assertIn(owner_line, legacy)
        runtime_path = PROJECT_ROOT / ".agents/skills" / skill / "SKILL.md"
        original = runtime_path.read_text(encoding="utf-8")
        runtime_path.write_text(legacy.replace(owner_line, "", 1), encoding="utf-8")
        try:
            receipt = classify_legacy(context, skill, expected)
        finally:
            runtime_path.write_text(original, encoding="utf-8")
        self.assertEqual(receipt["classification"], "legacy_schema_mismatch")
        self.assertEqual(receipt["resolution"], "blocked")
        self.assertGreater(len(receipt["unmatched_blocks"]), 0)

    def test_render_shim_contains_canonical_skill_dependency_manifest(self) -> None:
        """The generated discovery adapter emits the registered skill manifest."""
        context = build_context(PROJECT_ROOT)
        rendered = render_shim(build_record(context, "agent-orchestration"))
        self.assertIn(
            "\n".join(
                (
                    "<!--",
                    "@dependency-start",
                    "contract skill",
                    "responsibility Exposes agent-orchestration for runtime discovery.",
                    "upstream design ../../../agents/skills/agent-orchestration.md owner",
                    "@dependency-end",
                    "-->",
                )
            ),
            rendered,
        )


if __name__ == "__main__":
    unittest.main()
