"""Focused tests for the canonical requirements-lock parser."""

# @dependency-start
# contract test
# responsibility Verifies PEP 508 logical records, hash locks, comments, markers, and strict parser errors.
# upstream design ../../documents/design/devcontainer/parent-devcontainer-policy.md requirements lock parser ownership and checker projection
# upstream implementation ../../tools/agent_tools/requirements_lock.py canonical parser and result/error model
# @dependency-end

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from tools.agent_tools.requirements_lock import (  # pyright: ignore[reportMissingTypeStubs]
    RequirementErrorCode,
    parse_requirements,
)


class RequirementsLockTests(unittest.TestCase):
    """Verify the single owner of requirements-file parsing semantics."""

    def test_pip_compile_records_preserve_pep508_markers_and_hashes(self) -> None:
        """Parse normal pip-compile output into structured logical records."""
        requirements = (
            "# generated by pip-compile\n"
            "jupyterlab==1.2.3 ; python_version >= '3.0' \\\n"
            f"    --hash=sha256:{'A' * 64} \\\n"
            f"    --hash=sha256:{'b' * 64}  # via project\n"
            "notebook==1.0.0 \\\n"
            f"    --hash=sha256:{'c' * 64}\n"
            "ipykernel==1.0.0 \\\n"
            f"    --hash=sha256:{'d' * 64}\n"
            "pydeps==1.0.0 \\\n"
            f"    --hash=sha256:{'e' * 64}\n"
            "snakeviz==1.0.0 \\\n"
            f"    --hash=sha256:{'f' * 64}\n"
            "pyyaml==6.0.2 \\\n"
            f"    --hash=sha256:{'0' * 64}\n"
            'custom-visualizer @ https://example.invalid/tool.whl#sha256=abc123 ; python_version < "0"\n'
        )
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "requirements.txt"
            path.write_text(requirements, encoding="utf-8")

            result = parse_requirements(path)

        self.assertTrue(result.valid)
        self.assertEqual(len(result.records), 7)
        jupyterlab = result.records[0]
        self.assertEqual(jupyterlab.normalized_name, "jupyterlab")
        self.assertEqual(jupyterlab.marker, 'python_version >= "3.0"')
        self.assertEqual(
            tuple(item.digest for item in jupyterlab.hashes),
            ("a" * 64, "b" * 64),
        )
        self.assertEqual(
            result.records[-1].url, "https://example.invalid/tool.whl#sha256=abc123"
        )
        self.assertFalse(result.records[-1].is_active())

    def test_invalid_records_are_rejected_by_one_typed_error_model(self) -> None:
        """Reject every strict #490 failure branch through the owner result."""
        backslash = chr(92)
        cases = {
            "malformed continuation": (
                f"package==1.0 {backslash}\n    not-a-hash\n",
                RequirementErrorCode.MALFORMED_CONTINUATION,
            ),
            "orphan hash": (
                f"--hash=sha256:{'a' * 64}\n",
                RequirementErrorCode.ORPHAN_HASH,
            ),
            "malformed hash": (
                f"package==1.0 {backslash}\n    --hash=sha256:short\n",
                RequirementErrorCode.MALFORMED_HASH,
            ),
            "requirement option": (
                "--index-url https://pypi.org/simple\n",
                RequirementErrorCode.INVALID_OPTION,
            ),
            "unterminated continuation": (
                f"package==1.0 {backslash}\n",
                RequirementErrorCode.UNTERMINATED_CONTINUATION,
            ),
            "invalid PEP 508": (
                "not a requirement\n",
                RequirementErrorCode.INVALID_REQUIREMENT,
            ),
        }

        for name, (contents, code) in cases.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as temporary:
                path = Path(temporary) / "requirements.txt"
                path.write_text(contents, encoding="utf-8")

                result = parse_requirements(path)

            self.assertFalse(result.valid)
            self.assertEqual(tuple(error.code for error in result.errors), (code,))

    def test_comments_between_continuation_lines_are_rejected(self) -> None:
        """Do not silently detach a continued record from its hash lines."""
        backslash = chr(92)
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "requirements.txt"
            path.write_text(
                f"package==1.0 {backslash}\n# comment\n",
                encoding="utf-8",
            )

            result = parse_requirements(path)

        self.assertEqual(
            tuple(error.code for error in result.errors),
            (RequirementErrorCode.MALFORMED_CONTINUATION,),
        )


if __name__ == "__main__":
    unittest.main()
